### ISSUE TITLE
Error in compile.sh and run-compiler.sh when running in Ubuntu 14

### ISSUE THREAD

**Issue by caixiaomo1993** [oblivm/ObliVMLang#1]
In "compile.sh", 
javac -cp bin\;lib/\* -d bin @source.txt;
should be modified to be
javac -cp bin\:lib/\* -d bin @source.txt;

In "run-compiler.sh"
java -cp bin\;lib/\* com.oblivm.compiler.cmd.Cmd -o ./flexsc-bin/ $1;
should be modified as 
java -cp bin\:lib/\* com.oblivm.compiler.cmd.Cmd -o ./flexsc-bin/ $1;

Also, Oracle java rather than OpenJDK should be installed for compiling and running this programme, otherwise "Unsupported major.minor version 52.0" would appear.

**Comment by oblivm** [comment]
I've updated the compiler.sh and run-compiler.sh, and make separate files to work with cygwin.

I also update README requirement to include Oracle Java 8.

Thanks for your interest, and reporting this problem!

best,
Chang
